//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_PZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_cart
    {
        public string article { get; set; }
        public int count { get; set; }
        public int cart_id { get; set; }
    
        public virtual Carts Carts { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
